/* eslint-disable no-dupe-keys */
import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Joao Lopes",
      email: "joaorfclopes@gmail.com",
      phoneNumber: 910917510,
      password: bcrypt.hashSync("admin", 8),
      isAdmin: true,
    },
    {
      name: "Silvia Peralta",
      email: "sweevil.tattoos@gmail.com",
      phoneNumber: 916828734,
      password: bcrypt.hashSync("admin", 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Sweevil Long Sleeve",
      category: "Hoodies",
      images: [
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/longsleeve01.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/longsleeve02.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/longsleeve03.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/longsleeve04.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/longsleeve05.jpg",
      ],
      price: 35,
      description:
        "High quality serigraph printing. The model is 160cm tall and she's wearing a XL size",
      isClothing: true,
      countInStock: {
        stock: null,
        xs: null,
        s: null,
        m: null,
        l: 1,
        xl: 3,
        xxl: null,
      },
      visible: true,
    },
    {
      name: "Sweevil T-Shirt",
      category: "T-Shirts",
      images: [
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/teessweevil01.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/teessweevil02.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/teessweevil03.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/teessweevil04.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/teessweevil05.jpg",
      ],
      price: 30,
      description:
        "High quality serigraph printing; 100% cotton; The model is 160cm tall and she's wearing a XL size",
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 0,
        s: 5,
        m: 3,
        l: 5,
        xl: 3,
        xxl: 0,
      },
      visible: true,
    },
    {
      name: "Sweevil Tote Bag",
      category: "Bags",
      images: [
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tote01.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tote02.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tote03.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tote04.jpg",
      ],
      price: 20,
      description: "High quality serigraph printing. 100% cotton",
      isClothing: false,
      countInStock: {
        stock: 20,
        xs: null,
        s: null,
        m: null,
        l: null,
        xl: null,
        xxl: null,
      },
      visible: true,
    },
    {
      name: "Sweevil White T-Shirt",
      category: "T-Shirts",
      images: [
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/16imgsite.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/10imgsite.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/09imgsite.jpg",
      ],
      price: 15,
      description: "High quality serigraph printing. 100% cotton",
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 0,
        s: 5,
        m: 4,
        l: 0,
        xl: 0,
        xxl: 0,
      },
      visible: true,
    },
    {
      name: "Sweevil Black T-Shirt",
      category: "T-Shirts",
      images: [
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/13imgsite.jpg",
      ],
      price: 15,
      description: "High quality serigraph printing. 100% cotton",
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 0,
        s: 1,
        m: 0,
        l: 0,
        xl: 0,
        xxl: 0,
      },
      visible: true,
    },
    {
      name: "Sweevil Black Hoodie",
      category: "Hoodies",
      images: [
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/15imgsite.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/12imgsite.jpg",
      ],
      price: 60,
      description: "High quality serigraph printing. 100% cotton",
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 0,
        s: 0,
        m: 0,
        l: 0,
        xl: 0,
        xxl: 0,
      },
      visible: true,
    },
    {
      name: "The New Original Sin",
      category: "Paintings",
      images: [
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tela01.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tela02.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tela03.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tela04.jpg",
        "https://sweevil.s3.eu-west-3.amazonaws.com/store/tela05.jpg",
      ],
      price: 1500,
      description: "Acrylic on canvas - 95x75cm",
      isClothing: false,
      countInStock: {
        stock: 1,
        xs: null,
        s: null,
        m: null,
        l: null,
        xl: null,
        xxl: null,
      },
      visible: true,
    },
  ],
  galleryImages: [
    {
      description: "Portugal, 2021",
      image: "/images/tattoo15.jpg",
      category: "Tattoos",
    },
    {
      description: "“Vampira”, 2021. Digital comic",
      image: "/images/digital8.jpg",
      category: "Digital",
    },
    {
      description: "Portugal, 2021",
      image: "/images/tattoo10.jpg",
      category: "Tattoos",
    },
    {
      description: "Portugal, 2021",
      image: "/images/tattoo11.jpg",
      category: "Tattoos",
    },
    {
      description: "“It’s always you”, 2021. Digital comic",
      image: "/images/digital9.jpg",
      category: "Digital",
    },
    {
      description: "Portugal, 2021",
      image: "/images/tattoo12.jpg",
      category: "Tattoos",
    },
    {
      description: "Portugal, 2021",
      image: "/images/tattoo13.jpg",
      category: "Tattoos",
    },
    {
      description: "Portugal, 2021",
      image: "/images/tattoo14.jpg",
      category: "Tattoos",
    },
    {
      description: "“Mithya”, 2021. Digital comic",
      image: "/images/digital6.jpg",
      category: "Digital",
    },
    {
      description: "“Against the law”, 2020. Acrylic on paper",
      image: "/images/painting6.jpg",
      category: "Paintings",
    },
    {
      description: "“Isolation”, 2020. Acrylic on paper",
      image: "/images/painting2.jpg",
      category: "Paintings",
    },
    {
      description: "Portugal, 2020",
      image: "/images/tattoo4.jpg",
      category: "Tattoos",
    },
    {
      description: "Portugal, 2020",
      image: "/images/tattoo5.jpg",
      category: "Tattoos",
    },
    {
      description: "“The system”, 2020. Pencil ",
      image: "/images/painting3.jpg",
      category: "Paintings",
    },
    {
      description: "Portugal, 2020",
      image: "/images/tattoo6.jpg",
      category: "Tattoos",
    },
    {
      description: "“Strange box”, 2020. Acrylic on paper",
      image: "/images/painting4.jpg",
      category: "Paintings",
    },
    {
      description: "Portugal, 2020",
      image: "/images/tattoo7.jpg",
      category: "Tattoos",
    },
    {
      description:
        "“It didn’t came from outer space”, 2020. Digital illustration",
      image: "/images/digital2.jpg",
      category: "Digital",
    },
    {
      description: "“Reality is equilibrium”, 2020. Acrylic on paper",
      image: "/images/painting1.jpg",
      category: "Paintings",
    },
    {
      description:
        "Detail from “Reality is equilibrium”, 2020. Acrylic on paper",
      image: "/images/painting8.jpg",
      category: "Paintings",
    },
    {
      description: "Portugal, 2019",
      image: "/images/tattoo9.jpg",
      category: "Tattoos",
    },
    {
      description: "“We’re players”, 2020. Digital illustration",
      image: "/images/digital4.jpg",
      category: "Digital",
    },
    {
      description: "“Solid gold”, 2020. Acrylic on paper",
      image: "/images/painting9.jpg",
      category: "Paintings",
    },
    {
      description: "“Equilibrium is everywhere”, 2020. Digital illustration",
      image: "/images/digital1.jpg",
      category: "Digital",
    },
    {
      description: "“Illusion”, 2020. Acrylic on paper",
      image: "/images/painting10.jpg",
      category: "Paintings",
    },
    {
      description: "Portugal, 2020",
      image: "/images/tattoo1.jpg",
      category: "Tattoos",
    },
    {
      description: "“Transparency is all I see”, 2021. Digital comic",
      image: "/images/digital7.jpg",
      category: "Digital",
    },
    {
      description: "“The new original sin”, 2020. Acrylic on canvas",
      image: "/images/painting11.jpg",
      category: "Paintings",
    },
    {
      description: "Portugal, 2020",
      image: "/images/tattoo2.jpg",
      category: "Tattoos",
    },
    {
      description: "“Your Ego is not your Amigo”, 2021. Digital illustration",
      image: "/images/digital5.jpg",
      category: "Digital",
    },
    {
      description: "“Sinking”, 2020. Acrylic on paper",
      image: "/images/painting7.jpg",
      category: "Paintings",
    },
    {
      description: "“Wake up call”, 2020. Acrylic on paper",
      image: "/images/painting5.jpg",
      category: "Paintings",
    },
    {
      description: "Portugal, 2020",
      image: "/images/tattoo3.jpg",
      category: "Tattoos",
    },
    {
      _id: "602fd1e74704f500045ffc8d",
      description: "“The rebirthing”, 2020. Digital comic",
      image: "/images/digital3.jpg",
      category: "Digital",
    },
    {
      description: "Portugal, 2020",
      image: "/images/tattoo8.jpg",
      category: "Tattoos",
    },
  ],
};

export default data;
