/* eslint-disable no-dupe-keys */
import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Sweevil",
      email: "joaorfclopes@gmail.com",
      phoneNumber: 910917510,
      password: bcrypt.hashSync("admin", 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Bag",
      category: "Bags",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/bag1.jpg",
      finalPrice: 20,
      description: "high quality product",
      isClothing: false,
      countInStock: {
        stock: 10,
        xs: null,
        s: null,
        m: null,
        l: null,
        xl: null,
        xxl: null,
      },
    },
    {
      name: "Bag & T-Shirt",
      category: "T-Shirts",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/bag1%26tshirt4.jpg",
      finalPrice: 40,
      description: "high quality product",
      countInStock: 10,
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 10,
        s: 10,
        m: 10,
        l: 10,
        xl: 10,
        xxl: 10,
      },
    },
    {
      name: "Long Sleeve 1",
      category: "Hoodies",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/long-sleeve1.JPG",
      finalPrice: 40,
      description: "high quality product",
      countInStock: 10,
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 10,
        s: 10,
        m: 10,
        l: 10,
        xl: 10,
        xxl: 10,
      },
    },
    {
      name: "Long Sleeve 2",
      category: "Hoodies",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/long-sleeve2.JPG",
      finalPrice: 40,
      description: "high quality product",
      countInStock: 10,
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 10,
        s: 10,
        m: 10,
        l: 10,
        xl: 10,
        xxl: 10,
      },
    },
    {
      name: "T-Shirt 1",
      category: "T-Shirts",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/tshirt1.JPG",
      finalPrice: 30,
      description: "high quality product",
      countInStock: 10,
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 10,
        s: 10,
        m: 10,
        l: 10,
        xl: 10,
        xxl: 10,
      },
    },
    {
      name: "T-Shirt 2",
      category: "T-Shirts",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/tshirt2.JPG",
      finalPrice: 30,
      description: "high quality product",
      countInStock: 10,
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 10,
        s: 10,
        m: 10,
        l: 10,
        xl: 10,
        xxl: 10,
      },
    },
    {
      name: "T-Shirt 3 & 1",
      category: "T-Shirts",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/tshirt3%261.JPG",
      finalPrice: 30,
      description: "high quality product",
      countInStock: 10,
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 10,
        s: 10,
        m: 10,
        l: 10,
        xl: 10,
        xxl: 10,
      },
    },
    {
      name: "T-Shirt 4",
      category: "T-Shirts",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/tshirt4.JPG",
      finalPrice: 30,
      description: "high quality product",
      countInStock: 10,
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 10,
        s: 10,
        m: 10,
        l: 10,
        xl: 10,
        xxl: 10,
      },
    },
    {
      name: "T-Shirt 5",
      category: "T-Shirts",
      image:
        "https://sweevil-bucket.s3.eu-west-3.amazonaws.com/images/tshirt5.jpg",
      finalPrice: 30,
      description: "high quality product",
      countInStock: 10,
      isClothing: true,
      countInStock: {
        stock: null,
        xs: 10,
        s: 10,
        m: 10,
        l: 10,
        xl: 10,
        xxl: 10,
      },
    },
  ],
};
export default data;
